### ISSUE TITLE
Inability to pay some fee

### ISSUE THREAD

**Issue by ganesh1997oli** [Maar-io/hashlips-ui-for-ink#1]
I have fee i.e.`0.0160 SDN` in my `ACCOUNT 1 (SUBWALLET-JS)` wallet.

![1](https://user-images.githubusercontent.com/42571338/215958055-fd22ff59-8a8a-4fab-8cd3-806dc5cc517b.png)

When I tried to deploy smart contract it throws `Inability to pay fee`. I know Its because of low fee. But I am not able to get more test SDN token. I have used Astar portal but didn't get more than 0.007 in 1st attempt and can't able to use this more than one. Is there any possible way to get SDN test token?

**Comment by Maar-io** [comment]
Hi,
Shiden is a mainnet. There are no test tokens.
Please use Arthswap/cBridge or any CEX to purchase some tokens.

BR

**Comment by ganesh1997oli** [comment]
@Marr-io Are NFT minted with Shiden only appears in Subwall NFT section?
<img width="1440" alt="Screenshot 2023-02-01 at 13 14 11" src="https://user-images.githubusercontent.com/42571338/215979113-6a54fdca-0d5c-4a92-8962-298e9796927b.png">

**Comment by Maar-io** [comment]
yes, but you need to import contract address.
Use the link below 777, that will open subscan. Copy address from subscan and Use that address to import NFT to your SubWallet
